### ISSUE TITLE
Will it be open sourced?

### ISSUE THREAD

**Issue by tomisacat** [Tencent/OOMDetector#2]

**Comment by rosen0510** [comment]
What do you mean by “open sourced”？

**Comment by tomisacat** [comment]
Currently it's only a framework so I wonder will you consider to make it open source

**Comment by rosen0510** [comment]
It's already open sourced now,please check the "libOOMDetector" project.

**Comment by tomisacat** [comment]
My mistake, appreciate your work 👍
