### ISSUE TITLE
oom_file 为何为全 0 文件

### ISSUE THREAD

**Issue by Xwoder** [Tencent/OOMDetector#26]
在启用监控后，运行程序一段时间，显示 App 内存从 80M 暴增至 300M，随查看生成的名为的 `normal_malloc20180621_093431650.log` 的 `oom_file` 文件，结果显示该文件为 16 进制全 0 文件，字节数为 524KB，且多次此时该文件均为 524KB。

摘录如下

```
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
```

请问这种现象正常么，如何解决呢

**Comment by wuzhangping** [comment]
我也是遇到和你同样的问题，不知道你有没有找到解决方法

**Comment by wuzhangping** [comment]
刚刚发现是如果直接模拟内存暴增弄到crash，就会出现真正的crash日志了

**Comment by Virtue86** [comment]
确实。在内存达到设定峰值就出线日志了

**Comment by rosen0510** [comment]
必须要出现内存触顶后才会有日志

**Comment by Xwoder** [comment]
@rosen0510 谢谢，了解了。

**Comment by HePingLaoSan** [comment]
求教，我模拟了内存爆增的crash，但是导出来的log仍然是0000的 524KB大小的文件，不知道哪里出了问题，这是我的配置：

 ` OOMDetector *detector = [OOMDetector getInstance]; 

    [detector setupWithDefaultConfig];
    [detector startMaxMemoryStatistic:100*1024*1024];
    [detector setFileDataDelegate:nil];
    [detector setPerformanceDataDelegate:nil];
    [detector startSingleChunkMallocDetector:50*1024*1024 callback:^(size_t bytes, NSString *stack) {
        UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"大内存分配检测" message:stack preferredStyle:UIAlertControllerStyleAlert];
        UIAlertAction *cancel = [UIAlertAction actionWithTitle:@"cancel" style:UIAlertActionStyleCancel handler:nil];
        [alert addAction:cancel];
        [self.window.rootViewController presentViewController:alert animated:YES completion:nil];
    }];
    [detector startMallocStackMonitor:1*1024*1024 needAutoDumpWhenOverflow:YES dumpLimit:100*1024*1024 sampleInterval:0.1];
    [detector showMemoryIndicatorView:DEBUG]; `

**Comment by HePingLaoSan** [comment]
> 求教，我模拟了内存爆增的crash，但是导出来的log仍然是0000的 524KB大小的文件，不知道哪里出了问题，这是我的配置：
> 
> ` OOMDetector *detector = [OOMDetector getInstance];
> 
> ```
> [detector setupWithDefaultConfig];
> [detector startMaxMemoryStatistic:100*1024*1024];
> [detector setFileDataDelegate:nil];
> [detector setPerformanceDataDelegate:nil];
> [detector startSingleChunkMallocDetector:50*1024*1024 callback:^(size_t bytes, NSString *stack) {
>     UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"大内存分配检测" message:stack preferredStyle:UIAlertControllerStyleAlert];
>     UIAlertAction *cancel = [UIAlertAction actionWithTitle:@"cancel" style:UIAlertActionStyleCancel handler:nil];
>     [alert addAction:cancel];
>     [self.window.rootViewController presentViewController:alert animated:YES completion:nil];
> }];
> [detector startMallocStackMonitor:1*1024*1024 needAutoDumpWhenOverflow:YES dumpLimit:100*1024*1024 sampleInterval:0.1];
> [detector showMemoryIndicatorView:DEBUG]; `
> ```

看了下源码，我发现是我配置的原因导致日志没有写入，dumplimit的单位是mb，改小了数值后能在log中看到日志了，但是日志如图：
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/13445835/63838208-81768a00-c9af-11e9-8061-6d600706bc92.png">
请问这个日志是正确的吗？堆栈转写生成的文件体积是0K。。。
