### ISSUE TITLE
自家MLeaksFinder有的View和ViewController 的泄露检测,这个库里暂时不支持吗?

### ISSUE THREAD

**Issue by YangYouYong** [Tencent/OOMDetector#5]
view和viewController的内存泄露检测不到.

**Comment by rosen0510** [comment]
OOMDetector的泄漏检测原理和MLeaksFinder完全不同，主要用于检测“无主内存泄漏”，详细原理可参考这篇文章：https://juejin.im/post/5a58f1a76fb9a01cab283392

**Comment by YangYouYong** [comment]
晓得了,应用场景不一样.
